### ISSUE TITLE
fistlabs_unit_incoming cannot find module 'fist/core/fist-error'

### ISSUE THREAD

**Issue by gitim** [fistlabs/fist-fistlabs_unit_incoming#3]
The unit can't [require](https://github.com/fistlabs/fist-fistlabs_unit_incoming/blob/master/fistlabs_unit_incoming.js#L4) `fist/core/fist-error` since it was [moved](https://github.com/fistlabs/fist/blob/master/core/errors.js#L13) into `fist/core/errors`. Could you fix it and update in npm?

**Comment by golyshevd** [comment]
Thanks for bug report! Will be fixed soon!

**Comment by golyshevd** [comment]
0.0.3 now. Thanks for collaborating. Did not know that anybody interested in fist =)

**Comment by gitim** [comment]
Thanks!
